<?php

return [
    /*Ristorante Cinese */
    [
        "restaurant_id" => 0,
        "name" => "Riso Fritto alla Cantonese",
        "description" => "Riso saltato con uova, piselli, prosciutto e gamberi.",
        "price" => "8.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.tavolartegusto.it%2Fricetta%2Friso-alla-cantonese%2F&psig=AOvVaw2b3brqNYb5eSLw8DLrCyyb&ust=1732370523569000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLimr6GN8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 0,
        "name" => "Pollo al Limone",
        "description" => "Pollo fritto con salsa dolce al limone, accompagnato da riso bianco.",
        "price" => "9.00",
        "description" => "Pollo fritto con salsa dolce al limone, accompagnato da riso.",
        "price" => "€9,00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fricette.giallozafferano.it%2FPollo-al-limone.html&psig=AOvVaw3QHPl5w4sXwbIBOppoq0Jn&ust=1732370771151000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCJCfkMWQ8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 0,
        "name" => "Dim Sum Mix",
        "description" => "Ravioli cinesi al vapore (con carne di maiale e gamberi), porzione mista.",
        "price" => "12.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.tokopedia.com%2Fdapurkamii%2Fdimsum-mix-ayam-25-pcs%3Futm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_campaign%3Dpdp&psig=AOvVaw3jUEiOUY_vZH-WDHq227Kc&ust=1732371517728000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCMC3tPqQ8IkDFQAAAAAdAAAAABAJ",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 0,
        "name" => "Kung Pao Chicken",
        "description" => "Pollo in salsa piccante con arachidi, peperoncini secchi e verdure.",
        "price" => "10.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.chewoutloud.com%2Ffast-healthy-kung-pao-chicken-recipe%2F&psig=AOvVaw3F2i0sk9Wg2ttsHGV2jUV3&ust=1732371779812000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCKDfyfaR8IkDFQAAAAAdAAAAABAJ",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 0,
        "name" => "Involtini Primavera",
        "description" => "Involtini fritti con carne di maiale, verdure e salsa agrodolce.",
        "price" => "5.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fricette.giallozafferano.it%2FInvoltini-primavera.html&psig=AOvVaw011FJreAA2Xpmg2p4Wff8N&ust=1732371882469000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCIjX5aaS8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    /*Ristorante Giapponese */
    [
        "restaurant_id" => 1,
        "name" => "Sushi Maki Assortito",
        "description" => "Una selezione di maki (tonno, salmone, avocado, cetriolo).",
        "price" => "14.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fasushibuffet.com%2F1-assorted-sushi-maki-combination-34-pcs%2F&psig=AOvVaw3EkfrI22FMJcc83Kd0Jv90&ust=1732372321014000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLD57PiT8IkDFQAAAAAdAAAAABAJ",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 1,
        "name" => "Bento Box Special",
        "description" => "Box con sushi, tempura, insalata e riso.",
        "price" => "16.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.goenne.com%2Fpost%2Ftime-honored-tradition-meets-modern-convenience-the-benefits-of-a-wooden-bento-box&psig=AOvVaw0S68PE3hIGISmva0cghvyL&ust=1732372256151000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLiAq9qT8IkDFQAAAAAdAAAAABAY",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 1,
        "name" => "Ramen Tonkotsu (brodo separato)",
        "description" => "Noodles in brodo ricco, servito separato per mantenere la freschezza.",
        "price" => "12.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.foodandwine.com%2Ftonkotsu-ramen-7094539&psig=AOvVaw3yvkMHciJA6zuGXYIV6wAZ&ust=1732372187166000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCODW4riT8IkDFQAAAAAdAAAAABAR",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 1,
        "name" => "Gyoza alla Griglia",
        "description" => "Ravioli giapponesi ripieni di carne e verdure, dorati alla griglia.",
        "price" => "8.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fblog.giallozafferano.it%2Fcucinaregiapponese%2Fricetta-gyoza-con-pollo-e-funghi-shitake-alla-piastra%2F&psig=AOvVaw1yJj7fcTqutGd8O6V_i62i&ust=1732372141452000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNixzaOT8IkDFQAAAAAdAAAAABAY",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 1,
        "name" => "Sashimi Mistico",
        "description" => "Selezione di pesce crudo (tonno, salmone, branzino).",
        "price" => "18.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.gruppogermogli.it%2Fen%2Fprodotto%2Fsashimi-misto%2F&psig=AOvVaw2bVdNJ7bP_4B7HRqYlgBFd&ust=1732372107599000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLDm15KT8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    /*Ristorante Koreano */
    [
        "restaurant_id" => 2,
        "name" => "Bibimbap",
        "description" => "Riso misto con verdure, carne e uovo al centro, con salsa gochujang.",
        "price" => "11.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.stoneline.de%2Fit%2Fricette%2Fcoreano-bibimbap&psig=AOvVaw0HyvBMIZ8525H_LEg_QcHu&ust=1732372512175000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLi8o9OU8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 2,
        "name" => "Bulgogi Beef",
        "description" => "Carne di manzo marinata in salsa di soia e spezie, grigliata e servita con riso.",
        "price" => "13.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fcooking.nytimes.com%2Frecipes%2F1017444-bulgogi&psig=AOvVaw1ZqwVapsZvZwF9fbEynXHs&ust=1732372577399000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCJDnvvWU8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 2,
        "name" => "Kimchi Jjigae",
        "description" => "Zuppa di kimchi con tofu e carne di maiale.",
        "price" => "9.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.eatingwell.com%2Frecipe%2F7903590%2Fkimchi-jjigae%2F&psig=AOvVaw3pjDoAj4MFjy0_OpSLOktv&ust=1732372623930000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCJi_yYiV8IkDFQAAAAAdAAAAABAJ",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 2,
        "name" => "Japchae (Noodles di Patate Dolci)",
        "description" => "Noodles saltati con verdure, carne di manzo e salsa di soia.",
        "price" => "10.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.mangiarebene.com%2Fricette%2Fuova%2Fvermicelli-di-patate-dolci-saltati-con-carni-e-verdure-japchae&psig=AOvVaw3Peh4xFkZyDiRVS6ATN8rL&ust=1732372708724000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCMjM67GV8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 2,
        "name" => "Korean Fried Chicken",
        "description" => "Pollo fritto in stile coreano con salsa piccante o dolce.",
        "price" => "12.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.kitchensanctuary.com%2Fkorean-fried-chicken%2F&psig=AOvVaw3zhV4NQTAeM7pcyaCvpgOF&ust=1732372752887000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCPCwo8aV8IkDFQAAAAAdAAAAABAJ",
        "visibility" => true,
    ],
    /*Ristorante Messicano */
    [
        "restaurant_id" => 3,
        "name" => "Burrito de Carne Asada",
        "description" => "Burrito farcito con carne grigliata, riso, fagioli e salsa piccante.",
        "price" => "9.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.heinens.com%2Frecipes%2Fcarne-asada-burrito%2F&psig=AOvVaw34v17tGDHa6VNjnrBnNpjP&ust=1732372860373000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLifgvqV8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 3,
        "name" => "Tacos al Pastor",
        "description" => "Tacos con carne di maiale marinata, ananas, cipolla e coriandolo.",
        "price" => "8.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.culinaryhill.com%2Ftacos-al-pastor%2F&psig=AOvVaw0_PqTe44ZltVtREBNlhUv6&ust=1732372885449000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLidpoqW8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 3,
        "name" => "Quesadillas de Pollo",
        "description" => "Tortillas ripiene di pollo, formaggio e salsa, grigliate.",
        "price" => "7.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.annarecetasfaciles.com%2Fquesadilla-de-pollo.html&psig=AOvVaw3pCafPrDvKYxKYjWDJDpMM&ust=1732372942388000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCKiOzKCW8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 3,
        "name" => "Nachos Supreme",
        "description" => "Patatine di mais con formaggio fuso, guacamole, panna acida e salsa.",
        "price" => "7.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.delish.com%2Fcooking%2Frecipe-ideas%2Fa51518%2Fnachos-supreme-recipe%2F&psig=AOvVaw30blL6jzm20RaBXkpqa3gf&ust=1732373012046000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCPDmlMKW8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 3,
        "name" => "Churros con Salsa al Cioccolato",
        "description" => "Churros caldi con zucchero e cannella, accompagnati da salsa al cioccolato.",
        "price" => "5.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Ffooby.ch%2Fit%2Fricette%2F16925%2Fchurros-con-salsa-al-cioccolato-piccante&psig=AOvVaw182WojDOsIcZq_tnBWvcNQ&ust=1732373050638000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCOC0pdWW8IkDFQAAAAAdAAAAABAQ",
        "visibility" => true,
    ],
    /*Pizzeria */
    [
        "restaurant_id" => 4,
        "name" => "Pizza Margherita",
        "description" => "Pomodoro, mozzarella, basilico fresco e olio d'oliva.",
        "price" => "7.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fit.ooni.com%2Fblogs%2Frecipes%2Fmargherita-pizza&psig=AOvVaw1r51tuznlOHdbASiTz5sb1&ust=1732373481086000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNjE86GY8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 4,
        "name" => "Pizza Capricciosa",
        "description" => "Prosciutto cotto, funghi, carciofi, olive nere e mozzarella.",
        "price" => "9.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.buonissimo.it%2Flericette%2F5881_Pizza_capricciosa&psig=AOvVaw0l7qmBC5qzxpwKMbAP6M4y&ust=1732373456931000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCJjg9paY8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 4,
        "name" => "Pizza Quattro Stagioni",
        "description" => "Mozzarella, prosciutto, funghi, carciofi e olive.",
        "price" => "10.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.cookaround.com%2Fricetta%2FPizza-4-stagioni.html&psig=AOvVaw1-yv8Vb09r32ILMF8Y4a-M&ust=1732373437732000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCOjIoY2Y8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 4,
        "name" => "Calzone Ripieno",
        "description" => "Calzone con ricotta, mozzarella, prosciutto e funghi.",
        "price" => "9.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpepesangiovanni.it%2Fcalzone-ripieno%2F&psig=AOvVaw2Gc3hGNFhgiCobH5R-Wwh4&ust=1732373405792000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCMD50P6X8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 4,
        "name" => "Pizza Vegetariana",
        "description" => "Verdure grigliate (zucchine, melanzane, peperoni) con mozzarella. ",
        "price" => "8.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.guardini.com%2Fit%2Fricette%2Fpizza-vegetariana.html&psig=AOvVaw2sYNy3OUa1kNBHxQlx3eLH&ust=1732373377711000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCIib6--X8IkDFQAAAAAdAAAAABAQ",
        "visibility" => true,
    ],
    /*Ristorante Fusion */
    [
        "restaurant_id" => 5,
        "name" => "Sushi Burrito",
        "description" => "Rotolo di sushi grande con pesce crudo, avocado, riso e verdure, avvolto in alga nori. ",
        "price" => "10.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.eatbetter.de%2Frezepte%2Fsushi-burrito-knackig-frisch-genial-lecker&psig=AOvVaw3pQEvF5dnE9QJMnzFM2VuX&ust=1732373539387000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNDohr2Y8IkDFQAAAAAdAAAAABAf",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 5,
        "name" => "Tempura Tacos",
        "description" => "Gamberi e verdure in tempura serviti in tacos con salsa teriyaki.",
        "price" => "9.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vegkit.com%2Frecipes%2Ffreshly-picked-tempura-battered-eggplant-tacos%2F&psig=AOvVaw1wT9kbmo0BdfTCpywnUJlh&ust=1732373607695000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCIiCyt6Y8IkDFQAAAAAdAAAAABAZ",
        "visibility" => true,
    ],
    [
        "restaurant_id" => "",
        "name" => "Ramen Burger",
        "description" => "Un hamburger fatto con ramen, carne, lattuga e salsa speziata.",
        "price" => "12.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.eatfigsnotpigs.com%2Fasian-inspired-ramen-bun-burger-with-kimchi-slaw-wassabi-mayo-vegan-gf%2F&psig=AOvVaw21__3XIxcVhIQvKv_gXDn1&ust=1732373648561000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCJCb6fGY8IkDFQAAAAAdAAAAABAg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 5,
        "name" => "Poke Bowl Fusion",
        "description" => "Riso, pesce crudo, avocado, edamame, salsa di soia e zenzero.",
        "price" => "11.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fcookpad.com%2Fit%2Fricette%2F12810220-poke-bowl-fusion&psig=AOvVaw0oOJipEE74-ClKnVCe4vIX&ust=1732373734687000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCKi335qZ8IkDFQAAAAAdAAAAABAp",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 5,
        "name" => "Kimchi Quesadilla",
        "description" => "Tortilla ripiena di kimchi, formaggio fuso e carne di manzo.",
        "price" => "8.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fmissionfoodservice.com%2FRecipes%2FRecipeDetails%3Fname%3DKimchi%2BQuesadilla&psig=AOvVaw3NlhdBdOKjg9_s3isPfhB-&ust=1732373835991000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCPCq8sqZ8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    /*Ristorante Italiano */
    [
        "restaurant_id" => 6,
        "name" => "Lasagna alla Bolognese",
        "description" => "Lasagna con ragù di carne, besciamella e parmigiano.",
        "price" => "12.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.conad.it%2Fricette%2Fprimi-piatti%2Fal-forno%2Flasagne-alla-bolognese&psig=AOvVaw1FButpEi9QJCw5faHihGeP&ust=1732373961079000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCOjCoIia8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 6,
        "name" => "Ossobuco alla Milanese",
        "description" => "Stinco di vitello cotto con salsa gremolada, servito con risotto alla milanese.",
        "price" => "16.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.cucchiaio.it%2Fricetta%2Fricetta-ossibuchi-milanese%2F&psig=AOvVaw0MKYaUvpCMC_fIIff7U1bN&ust=1732374019058000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCICZgaSa8IkDFQAAAAAdAAAAABAJ",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 6,
        "name" => "Risotto ai Funghi Porcini",
        "description" => "Risotto cremoso con funghi porcini freschi e parmigiano.",
        "price" => "11.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fricette.giallozafferano.it%2FRisotto-ai-funghi-porcini.html&psig=AOvVaw1kaKASkx4gWJkYZLlewxPl&ust=1732374094099000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCJCpg8aa8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 6,
        "name" => "Polpette al Sugo",
        "description" => "Polpette di carne in sugo di pomodoro, servite con contorno di purè.",
        "price" => "9.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fricette.giallozafferano.it%2FPolpette-al-sugo.html&psig=AOvVaw2iwiDOY2pOO5L3mv13Z0R6&ust=1732374146988000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLC1xOqa8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 6,
        "name" => "Tiramisù",
        "description" => "Il classico dolce italiano con mascarpone, caffè e cacao.",
        "price" => "5.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.cookaround.com%2Fricetta%2Ftiramisu-classico.html&psig=AOvVaw1I07XOwXAGaY9sZkykYrZr&ust=1732374219339000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCODJ6oOb8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    /*Kebab */
    [
        "restaurant_id" => 7,
        "name" => "Kebap di Agnello",
        "description" => "Spiedini di carne di agnello marinata, grigliata e servita con riso o pane.",
        "price" => "10.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.agrodolce.it%2Fricette%2Fshish-kebab-di-agnello&psig=AOvVaw0NnvG4km8J9lnKwOZUK2kM&ust=1732374283623000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCPC3pKWb8IkDFQAAAAAdAAAAABAY",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 7,
        "name" => "Durum Kebab",
        "description" => "Carne di manzo o pollo, verdure e salsa in un piadina turca avvolta.",
        "price" => "8.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Froyalkebab-pizzeria.ch%2Fproduct%2Fkebab-dueruem%2F&psig=AOvVaw3vX4VRzzmshgphL13Xvd9G&ust=1732374365701000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLCR0-ab8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 7,
        "name" => "Falafel con Hummus",
        "description" => "Polpette di ceci servite con hummus e pita.",
        "price" => "7.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.hellofresh.it%2Frecipes%2Ffalafel-fritti-su-hummus-di-carote-660bc5939b244e4ad68f296b&psig=AOvVaw34dTxqLDf56tSreWi3UWNJ&ust=1732374515115000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCKjsgI-c8IkDFQAAAAAdAAAAABAJ",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 7,
        "name" => "Adana Kebab",
        "description" => "Carne di manzo e agnello macinata, speziata e grigliata su spiedo.",
        "price" => "9.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fturkishfoodie.com%2Fadana-kebab%2F&psig=AOvVaw3IKX_iN-76_XLQ2XyL-bxZ&ust=1732374576839000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCIDU7auc8IkDFQAAAAAdAAAAABAQ",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 7,
        "name" => "Baklava",
        "description" => "Dolci turchi con pasta filo, noci e sciroppo dolce.",
        "price" => "4.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.chefkoch.de%2Frezepte%2F1582931265789857%2FBaklava.html&psig=AOvVaw2IF8a91VCF4Fw4yZa-9UNF&ust=1732374638068000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCOCqwMmc8IkDFQAAAAAdAAAAABAJ",
        "visibility" => true,
    ],
    /*Gelateria */
    [
        "restaurant_id" => 8,
        "name" => "Coppa Gelato (3 Gusti)",
        "description" => "Gelato artigianale a scelta tra cioccolato, vaniglia, fragola, pistacchio, e altri gusti stagionali.",
        "price" => "5.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fit%2Fimmagine%2Fcoppa-gelato&psig=AOvVaw1YbN9DZQOXJGB93RXCgyzb&ust=1732374748194000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCIj47P-c8IkDFQAAAAAdAAAAABAJ",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 8,
        "name" => "Granita Siciliana",
        "description" => "Granita fresca al limone o alla fragola, servita con brioche.",
        "price" => "4.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fclaudiafornaciari.it%2Fricette%2Fgranita-siciliana-al-pistacchio%2F&psig=AOvVaw2RwGtfpcSP-UHK6Qnc0lue&ust=1732374855358000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCOjun7Kd8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 8,
        "name" => "Coppetta Affogato al Caffè",
        "description" => "Gelato alla vaniglia con caffè caldo versato sopra.",
        "price" => "6.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.ilgiornaledelcibo.it%2Faffogato-al-caffe-ricette%2F&psig=AOvVaw2t6vlXn8v5cT1hTxmQ7ghD&ust=1732374918655000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLiLmM-d8IkDFQAAAAAdAAAAABAQ",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 8,
        "name" => "Gelato al Pistacchio",
        "description" => "Gelato artigianale al pistacchio siciliano, ricco e cremoso.",
        "price" => "5.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.cucchiaio.it%2Fricetta%2Fgelato-al-pistacchio%2F&psig=AOvVaw2anuhibGDhq9SN7gk59Dor&ust=1732374952864000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCMDpqd-d8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 8,
        "name" => "Cialda con Gelato",
        "description" => "Gelato servito in una cialda croccante con topping a scelta (cioccolato, frutta, granella).",
        "price" => "4.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.ilgiornaledelcibo.it%2Fcome-fare-cono-gelato-a-casa%2F&psig=AOvVaw0NiPPaSdmCGiw8IUr5OAC5&ust=1732375023927000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNDHj4Ke8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    /*Pasticceria*/
    [
        "restaurant_id" => 9,
        "name" => "Cannoli Siciliani",
        "description" => "Cialde croccanti ripiene di ricotta, zucchero e gocce di cioccolato.",
        "price" => "3.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fricette.giallozafferano.it%2FCannoli-siciliani.html&psig=AOvVaw1gCOOy1tkRaOO-VUjB2Gtw&ust=1732375052651000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNj4u46e8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 9,
        "name" => "Torta al Limone",
        "description" => "Torta soffice al limone con crema e glassa.",
        "price" => "4.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fricette.giallozafferano.it%2FTorta-soffice-al-limone.html&psig=AOvVaw0HgsYJY2pwfcVuqub9SlmJ&ust=1732375131925000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCPCysbSe8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 9,
        "name" => "Croissant alla Crema",
        "description" => "Cornetto morbido ripieno di crema pasticcera.",
        "price" => "2.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.ilclubdellericette.it%2Fricetta%2Fcornetti-alla-crema&psig=AOvVaw0lxODcJX7DB7TdtN-XergL&ust=1732375162830000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCMDkzMOe8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 9,
        "name" => "Tiramisù Monoporzione",
        "description" => "Piccola porzione del classico dolce italiano con mascarpone, caffè e cacao.",
        "price" => "4.50",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.gattullo.it%2Ftiramisu-monoporzione-con-miscela-di-caffe-arabica%2F&psig=AOvVaw39u27FzMfxaVh0sUKl5sGy&ust=1732375403293000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCIj_hraf8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 9,
        "name" => "Biscotti di Pasta Frolla",
        "description" => "Biscotti freschi e friabili, ottimi per accompagnare il tè o il caffè.",
        "price" => "2.00",
        "image" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpaneangeli.it%2Fricetta%2Fbiscotti-di-pasta-frolla&psig=AOvVaw3bS52xW0wmuAL_1xCWQvya&ust=1732375371143000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCJCjuKaf8IkDFQAAAAAdAAAAABAE",
        "visibility" => true,
    ],



]




    ?>