<?php

return [
    /*Ristorante Cinese */
    [
        "restaurant_id" => 10,
        "category_id" => 4,
        "name" => "Riso Fritto alla Cantonese",
        "description" => "Riso saltato con uova, piselli, prosciutto e gamberi.",
        "price" => "8.50",
        "image" => "https://www.giallozafferano.it/images/229-22992/Riso-alla-cantonese_450x300.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 10,
        "category_id" => 4,
        "name" => "Pollo al Limone",
        "description" => "Pollo fritto con salsa dolce al limone, accompagnato da riso bianco.",
        "price" => "9.00",
        "image" => "https://www.giallozafferano.it/images/235-23580/Pollo-al-limone_450x300.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 10,
        "category_id" => 4,
        "name" => "Dim Sum Mix",
        "description" => "Ravioli cinesi al vapore (con carne di maiale e gamberi), porzione mista.",
        "price" => "12.00",
        "image" => "https://yoursushiroma.it/wp-content/uploads/2017/09/Dim-Sum-Mix-web.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 10,
        "category_id" => 4,
        "name" => "Kung Pao Chicken",
        "description" => "Pollo in salsa piccante con arachidi, peperoncini secchi e verdure.",
        "price" => "10.00",
        "image" => "https://www.seriouseats.com/thmb/_hMTqVpapsx30jF_31xmKEuhQ5s=/750x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2014__07__2021-02-12-Take-Out-Kung-Pao-Chicken-MHOM-11-c46f6c06713c45c5a287ddbf08779d04.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 10,
        "category_id" => 4,
        "name" => "Involtini Primavera",
        "description" => "Involtini fritti con carne di maiale, verdure e salsa agrodolce.",
        "price" => "5.00",
        "image" => "https://www.giallozafferano.it/images/230-23004/Involtini-primavera_450x300.jpg",
        "visibility" => true,
    ],
    /*Ristorante Giapponese */
    [
        "restaurant_id" => 1,
        "category_id" => 2,
        "name" => "Sushi Maki Assortito",
        "description" => "Una selezione di maki (tonno, salmone, avocado, cetriolo).",
        "price" => "14.50",
        "image" => "https://static.vecteezy.com/ti/foto-gratuito/p1/32700113-alto-giapponese-sushi-cibo-maki-ands-rotoli-con-salmone-gamberetto-granchio-e-avocado-superiore-visualizza-di-assortito-sushi-tutti-voi-puo-mangiare-menu-arcobaleno-sushi-rotolo-uramaki-hosomaki-e-nigiri-foto.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 1,
        "category_id" => 2,
        "name" => "Bento Box Special",
        "description" => "Box con sushi, tempura, insalata e riso.",
        "price" => "16.00",
        "image" => "https://www.luxurypretaporter.it/wp-content/uploads/2020/12/BENTO-DELIVERY-TENOHA2.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 1,
        "category_id" => 2,
        "name" => "Ramen Tonkotsu (brodo separato)",
        "description" => "Noodles in brodo ricco, servito separato per mantenere la freschezza.",
        "price" => "12.50",
        "image" => "https://www.seriouseats.com/thmb/IBikLAGkkP2QVaF3vLIk_LeNqHM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/rich-and-creamy-tonkotsu-ramen-broth-from-scratch-recipe-Diana-Chistruga-hero-6d318fadcca64cc9ac3e1c40fc7682fb.JPG",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 1,
        "category_id" => 2,
        "name" => "Gyoza alla Griglia",
        "description" => "Ravioli giapponesi ripieni di carne e verdure, dorati alla griglia.",
        "price" => "8.00",
        "image" => "https://kingu.it/wp-content/uploads/2022/09/Gyoza-gamberi.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 1,
        "category_id" => 2,
        "name" => "Sashimi Mistico",
        "description" => "Selezione di pesce crudo (tonno, salmone, branzino).",
        "price" => "18.00",
        "image" => "https://www.passionegourmet.it/wp-content/uploads/2015/11/BAS19LC.jpg",
        "visibility" => true,
    ],
    /*Ristorante Koreano */
    [
        "restaurant_id" => 2,
        "category_id" => 5,
        "name" => "Bibimbap",
        "description" => "Riso misto con verdure, carne e uovo al centro, con salsa gochujang.",
        "price" => "11.00",
        "image" => "https://upload.wikimedia.org/wikipedia/commons/4/44/Dolsot-bibimbap.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 2,
        "category_id" => 5,
        "name" => "Bulgogi Beef",
        "description" => "Carne di manzo marinata in salsa di soia e spezie, grigliata e servita con riso.",
        "price" => "13.50",
        "image" => "https://www.allrecipes.com/thmb/G_UXncCchkMVeELX8DQMEwJOdHI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/246172-Easy-Bulgogi-ddmfs-104-4x3-1-c0ddcab340474175a5d1c96bc2edabbc.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 2,
        "category_id" => 5,
        "name" => "Kimchi Jjigae",
        "description" => "Zuppa di kimchi con tofu e carne di maiale.",
        "price" => "9.50",
        "image" => "https://www.agrodolce.it/app/uploads/2020/11/kimchi-jjigae-2020-i-0146.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 2,
        "category_id" => 5,
        "name" => "Japchae (Noodles di Patate Dolci)",
        "description" => "Noodles saltati con verdure, carne di manzo e salsa di soia.",
        "price" => "10.00",
        "image" => "https://imgstore.sndimg.com/magnolia/images/b5a47774-8935-4b1c-b578-a452d2b0d17c.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 2,
        "category_id" => 5,
        "name" => "Korean Fried Chicken",
        "description" => "Pollo fritto in stile coreano con salsa piccante o dolce.",
        "price" => "12.00",
        "image" => "https://www.kitchensanctuary.com/wp-content/uploads/2019/08/Korean-Fried-Chicken-square-FS-New-7377.jpg",
        "visibility" => true,
    ],
    /*Ristorante Messicano */
    [
        "restaurant_id" => 3,
        "category_id" => 3,
        "name" => "Burrito de Carne Asada",
        "description" => "Burrito farcito con carne grigliata, riso, fagioli e salsa piccante.",
        "price" => "9.50",
        "image" => "https://www.heinens.com/content/uploads/2020/08/Carne-Asada-Burrito_800x550.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 3,
        "category_id" => 3,
        "name" => "Tacos al Pastor",
        "description" => "Tacos con carne di maiale marinata, ananas, cipolla e coriandolo.",
        "price" => "8.00",
        "image" => "https://www.seriouseats.com/thmb/4kbwN13BlZnZ3EywrtG2AzCKuYs=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20210712-tacos-al-pastor-melissa-hom-seriouseats-37-f72cdd02c9574bceb1eef1c8a23b76ed.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 3,
        "category_id" => 3,
        "name" => "Quesadillas de Pollo",
        "description" => "Tortillas ripiene di pollo, formaggio e salsa, grigliate.",
        "price" => "7.00",
        "image" => "https://i.ytimg.com/vi/9Yy9JIvi0_U/maxresdefault.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 3,
        "category_id" => 3,
        "name" => "Nachos Supreme",
        "description" => "Patatine di mais con formaggio fuso, guacamole, panna acida e salsa.",
        "price" => "7.50",
        "image" => "https://hips.hearstapps.com/hmg-prod/images/nachos-supreme-secondary-66154d44214ee.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 3,
        "category_id" => 3,
        "name" => "Churros con Salsa al Cioccolato",
        "description" => "Churros caldi con zucchero e cannella, accompagnati da salsa al cioccolato.",
        "price" => "5.00",
        "image" => "https://d2sj0xby2hzqoy.cloudfront.net/kenwood_italy/attachments/data/000/007/262/medium/churros-con-salsa-al-cioccolato.jpg",
        "visibility" => true,
    ],
    /*Pizzeria */
    [
        "restaurant_id" => 4,
        "category_id" => 1,
        "name" => "Pizza Margherita",
        "description" => "Pomodoro, mozzarella, basilico fresco e olio d'oliva.",
        "price" => "7.50",
        "image" => "https://www.reggiadicasertaunofficial.it/wp-content/uploads/pizza-margherita-la-vera-storia.webp",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 4,
        "category_id" => 1,
        "name" => "Pizza Capricciosa",
        "description" => "Prosciutto cotto, funghi, carciofi, olive nere e mozzarella.",
        "price" => "9.00",
        "image" => "https://primochef.it/wp-content/uploads/2018/05/SH_pizza_capricciosa.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 4,
        "category_id" => 1,
        "name" => "Pizza Quattro Stagioni",
        "description" => "Mozzarella, prosciutto, funghi, carciofi e olive.",
        "price" => "10.00",
        "image" => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144880/hd750x421.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 4,
        "category_id" => 1,
        "name" => "Calzone Ripieno",
        "description" => "Calzone con ricotta, mozzarella, prosciutto e funghi.",
        "price" => "9.50",
        "image" => "https://recipesblob.paneangeli.it/assets/80d5605863064425b82894dc4162cdc4/1272x764/calzone-ripieno-ricjpg.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 4,
        "category_id" => 1,
        "name" => "Pizza Vegetariana",
        "description" => "Verdure grigliate (zucchine, melanzane, peperoni) con mozzarella. ",
        "price" => "8.00",
        "image" => "https://www.guardini.com/images/guardinispa/ricette/full/pizza_set_2021_full.jpg",
        "visibility" => true,
    ],
    /*Ristorante Fusion */
    [
        "restaurant_id" => 5,
        "category_id" => 6,
        "name" => "Sushi Burrito",
        "description" => "Rotolo di sushi grande con pesce crudo, avocado, riso e verdure, avvolto in alga nori. ",
        "price" => "10.50",
        "image" => "https://www.cucchiaio.it/content/cucchiaio/it/ricette/2018/03/sushi-burrito/_jcr_content/header-par/image-single.img.jpg/1520441318780.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 5,
        "category_id" => 6,
        "name" => "Tempura Tacos",
        "description" => "Gamberi e verdure in tempura serviti in tacos con salsa teriyaki.",
        "price" => "9.00",
        "image" => "https://www.carnaldish.com/wp-content/uploads/2015/09/crispyfishtaco1.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 5,
        "category_id" => 6,
        "name" => "Ramen Burger",
        "description" => "Un hamburger fatto con ramen, carne, lattuga e salsa speziata.",
        "price" => "12.00",
        "image" => "https://img.taste.com.au/-K95Ndvh/taste/2016/11/ramen-burger-109717-1.jpeg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 5,
        "category_id" => 6,
        "name" => "Poke Bowl Fusion",
        "description" => "Riso, pesce crudo, avocado, edamame, salsa di soia e zenzero.",
        "price" => "11.50",
        "image" => "https://img-global.cpcdn.com/recipes/46be0d7596af5e5e/680x482cq70/poke-bowl-fusion-recipe-main-photo.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 5,
        "category_id" => 6,
        "name" => "Kimchi Quesadilla",
        "description" => "Tortilla ripiena di kimchi, formaggio fuso e carne di manzo.",
        "price" => "8.50",
        "image" => "https://www.siftandsimmer.com/wp-content/uploads/2022/07/kimchi-chicken-quesadillas-featured.jpg",
        "visibility" => true,
    ],
    /*Ristorante Italiano */
    [
        "restaurant_id" => 6,
        "category_id" => 1,
        "name" => "Lasagna alla Bolognese",
        "description" => "Lasagna con ragù di carne, besciamella e parmigiano.",
        "price" => "12.00",
        "image" => "https://www.cucchiaio.it/content/cucchiaio/it/ricette/2009/12/ricetta-lasagne-bolognese/_jcr_content/header-par/image_single.img.jpg/1462958827968.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 6,
        "category_id" => 1,
        "name" => "Ossobuco alla Milanese",
        "description" => "Stinco di vitello cotto con salsa gremolada, servito con risotto alla milanese.",
        "price" => "16.50",
        "image" => "https://media-assets.lacucinaitaliana.it/photos/635169cdbc2c8a8e10d1f342/16:9/w_2560%2Cc_limit/GettyImages-482478191.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 6,
        "category_id" => 1,
        "name" => "Risotto ai Funghi Porcini",
        "description" => "Risotto cremoso con funghi porcini freschi e parmigiano.",
        "price" => "11.00",
        "image" => "https://oliofarchioni.com/wp-content/uploads/2021/09/risotto-ai-funghi-porcini-1.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 6,
        "category_id" => 1,
        "name" => "Polpette al Sugo",
        "description" => "Polpette di carne in sugo di pomodoro, servite con contorno di purè.",
        "price" => "9.50",
        "image" => "https://www.cucchiaio.it/content/cucchiaio/it/ricette/2018/11/polpette-al-sugo/_jcr_content/header-par/image-single.img.jpg/1541764256677.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 6,
        "category_id" => 1,
        "name" => "Tiramisù",
        "description" => "Il classico dolce italiano con mascarpone, caffè e cacao.",
        "price" => "5.50",
        "image" => "https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2024/07/tiramisu-finale.jpeg",
        "visibility" => true,
    ],
    /*Kebab */
    [
        "restaurant_id" => 7,
        "category_id" => 3,
        "name" => "Kebap di Agnello",
        "description" => "Spiedini di carne di agnello marinata, grigliata e servita con riso o pane.",
        "price" => "10.00",
        "image" => "https://cdn.agrodolce.it/HMeypMq1kgkV97QHL1bNO-sgKR8=/2300x1294/smart/https://www.agrodolce.it/app/uploads/2018/08/084-18-Shish-kebab-di-agnello.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 7,
        "category_id" => 3,
        "name" => "Durum Kebab",
        "description" => "Carne di manzo o pollo, verdure e salsa in un piadina turca avvolta.",
        "price" => "8.50",
        "image" => "https://isturkkebabpizza.com/wp-content/uploads/2024/06/3.webp",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 7,
        "category_id" => 3,
        "name" => "Falafel con Hummus",
        "description" => "Polpette di ceci servite con hummus e pita.",
        "price" => "7.50",
        "image" => "https://img.hellofresh.com/f_auto,fl_lossy,q_auto,w_1200/hellofresh_s3/image/HF_Y24_R14_W27_IT_IT23255-2_Main_low-4002e116.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 7,
        "category_id" => 3,
        "name" => "Adana Kebab",
        "description" => "Carne di manzo e agnello macinata, speziata e grigliata su spiedo.",
        "price" => "9.50",
        "image" => "https://www.seriouseats.com/thmb/IVzgrLg6lmc_VvMjsfZAxI6Cx3E=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2014__04__20140428-adana-kebab-22-2f4debebf43d462ba045e041a9e9add4.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 7,
        "category_id" => 3,
        "name" => "Baklava",
        "description" => "Dolci turchi con pasta filo, noci e sciroppo dolce.",
        "price" => "4.00",
        "image" => "https://www.tavolartegusto.it/wp/wp-content/uploads/2022/08/Baklava.jpg",
        "visibility" => true,
    ],
    /*Gelateria */
    [
        "restaurant_id" => 8,
        "category_id" => 1,
        "name" => "Coppa Gelato (3 Gusti)",
        "description" => "Gelato artigianale a scelta tra cioccolato, vaniglia, fragola, pistacchio, e altri gusti stagionali.",
        "price" => "5.00",
        "image" => "https://media-assets.lacucinaitaliana.it/photos/61faffc188fb17b116c42ae1/3:2/w_1599,h_1066,c_limit/coppa-gelato-mangia-bevi.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 8,
        "category_id" => 1,
        "name" => "Granita Siciliana",
        "description" => "Granita fresca al limone o alla fragola, servita con brioche.",
        "price" => "4.00",
        "image" => "https://claudiafornaciari.it/wp-content/uploads/2018/10/granita-siciliana-pistacchio-Bronte-4.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 8,
        "category_id" => 1,
        "name" => "Coppetta Affogato al Caffè",
        "description" => "Gelato alla vaniglia con caffè caldo versato sopra.",
        "price" => "6.00",
        "image" => "https://www.ilgiornaledelcibo.it/wp-content/uploads/2020/06/affogato-al-caffe-decorazione.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 8,
        "category_id" => 1,
        "name" => "Gelato al Pistacchio",
        "description" => "Gelato artigianale al pistacchio siciliano, ricco e cremoso.",
        "price" => "5.50",
        "image" => "https://www.cucchiaio.it/content/cucchiaio/it/ricette/2021/06/gelato-al-pistacchio/_jcr_content/header-par/image-single.img.jpg/1624302766808.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 8,
        "category_id" => 1,
        "name" => "Cialda con Gelato",
        "description" => "Gelato servito in una cialda croccante con topping a scelta (cioccolato, frutta, granella).",
        "price" => "4.00",
        "image" => "https://www.cuocicuoci.com/wp-content/uploads/2021/08/cialda-da-pasticceria-gelato-scaled.jpg",
        "visibility" => true,
    ],
    /*Pasticceria*/
    [
        "restaurant_id" => 9,
        "category_id" => 1,
        "name" => "Cannoli Siciliani",
        "description" => "Cialde croccanti ripiene di ricotta, zucchero e gocce di cioccolato.",
        "price" => "3.50",
        "image" => "https://www.cucchiaio.it/content/cucchiaio/it/ricette/2015/11/cannoli-siciliani/_jcr_content/header-par/image-single.img.jpg/1448891641713.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 9,
        "category_id" => 1,
        "name" => "Torta al Limone",
        "description" => "Torta soffice al limone con crema e glassa.",
        "price" => "4.00",
        "image" => "https://www.giallozafferano.it/images/225-22570/Torta-soffice-al-limone_650x433_wm.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 9,
        "category_id" => 1,
        "name" => "Croissant alla Crema",
        "description" => "Cornetto morbido ripieno di crema pasticcera.",
        "price" => "2.50",
        "image" => "https://www.pasticceriatagliafico.it/Uploads/Small/croissant-crema-3_120_s.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 9,
        "category_id" => 1,
        "name" => "Tiramisù Monoporzione",
        "description" => "Piccola porzione del classico dolce italiano con mascarpone, caffè e cacao.",
        "price" => "4.50",
        "image" => "https://www.gattullo.it/wp-content/uploads/2023/05/tiramisu-monoporzione.jpg",
        "visibility" => true,
    ],
    [
        "restaurant_id" => 9,
        "category_id" => 1,
        "name" => "Biscotti di Pasta Frolla",
        "description" => "Biscotti freschi e friabili, ottimi per accompagnare il tè o il caffè.",
        "price" => "2.00",
        "image" => "https://www.cucchiaio.it/content/cucchiaio/it/articoli/2023/06/32-biscotti-di-pasta-frolla/jcr:content/page_images/ogImage.img10.jpg/1687266710720.jpg",
        "visibility" => true,
    ],



];